title: LittleControl'Blog
description: LittleControl'Blog
theme: just-the-docs

url: https://littlecontrol.github.io

aux_links:
  Template Repository: https://github.com/littlecontrol

plugins:
  - jekyll-default-layout
