title: LittleControl'Blog
description: LittleControl'Blog
theme: just-the-docs

baseurl: ""
url: https://blog.littlecontrol.me

# aux_links:
#   Template Repository: https://github.com/littlecontrol

plugins:
  - jekyll-default-layout
  # - jekyll-seo-tag
  # - jekyll-github-metadata
